### PR TITLE
Char count

### PR DESCRIPTION
**Pull request by dmundra**
Closes https://github.com/GSA/openacr/issues/243

Works exactly as requested. Give it a whirl!

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford can you review these changes? https://gsa.github.io/openacr-editor/

**Comment by mgifford** [comment]
Two issues I've noticed

This test should still meet color contrast requirements:
https://contrast-ratio.com/#orange-on-%23d0e1f1 (or white)
https://contrast-ratio.com/#green-on-%23d0e1f1

Orange is tough to get the contrast right.

And we need ARIA-live announcements to make these notices accessible. A polite alert should be given to screen readers.

**Comment by dmundra** [comment]
> Two issues I've noticed
> 
> This test should still meet color contrast requirements: https://contrast-ratio.com/#orange-on-%23d0e1f1 (or white) https://contrast-ratio.com/#green-on-%23d0e1f1
> 
> Orange is tough to get the contrast right.

Interesting. I took the color idea from WCAG but I can make the adjustment to it.

> 
> And we need ARIA-live announcements to make these notices accessible. A polite alert should be given to screen readers.

Will add this.

**Comment by dmundra** [comment]
@mgifford replaced orange with `.text-accent-warm-darker` (https://designsystem.digital.gov/utilities/color/) from USWDS (https://contrast-ratio.com/#%23775540-on-%23d0e1f1). Does that work?

Also added aria-polite.

**Comment by mgifford** [comment]
I tested it with VoiceOver and the ARIA looks good to me.  Let's add it as is and we can review it later if need be.

**Review by mgifford — DISMISSED** [review]
Approved with ARIA & new color contrast

**Comment by dmundra** [comment]
> I tested it with VoiceOver and the ARIA looks good to me. Let's add it as is and we can review it later if need be.

Can you try with an existing report and loading in a chapter page. It kept reading out 'Good' and 'Longer description may be helpful' multiple times for me.

**Comment by mgifford** [comment]
Ok, if you want to test it that way, it is really annoying.

The ARIA-live should only be spit out when the input box has focus. You are absolutely right that it is very annoying when you expand the page and then suddenly get notices with no context about all of the elements on the page.

Maybe we should remove this ARIA for now unless there is an easy way to just add it when engaging with that specific form element.

**Comment by dmundra** [comment]
> Maybe we should remove this ARIA for now unless there is an easy way to just add it when engaging with that specific form element.

Agreed @mgifford. I think when we do more validation messages we can do inline error-messages but also inline warning-messages and redo this message with that. I found Hidde's post on the topic https://hiddedevries.nl/en/blog/2017-04-04-how-to-make-inline-error-messages-accessible

**Comment by dmundra** [comment]
@mgifford I found this https://designsystem.digital.gov/components/character-count/. Maybe I can implement our message following their method and see if that works better.

**Comment by dmundra** [comment]
@mgifford switched to more dynamic version that only shows the message after you have made changes to the note. It is not as dynamic as the last one but works better. It is essentially a version of validation. Let me know if it works better.

**Comment by mgifford** [comment]
It doesn't really work though with this delay.  I forget what the character length is, but right now you only get the notice after you've left the input box. Also, you VoiceOver gets the notice that it is good, it is more associated with the link than the form that they just left.

If the limit is 200 characters, the "needs to be longer" to "good" has to be announced while you're typing very close to the 200 character range.

**Comment by dmundra** [comment]
> It doesn't really work though with this delay. I forget what the character length is, but right now you only get the notice after you've left the input box. Also, you VoiceOver gets the notice that it is good, it is more associated with the link than the form that they just left.

I figured that could be the case. I can change the code to handle it on keyup. Pushing that change now.

> If the limit is 200 characters, the "needs to be longer" to "good" has to be announced while you're typing very close to the 200 character range.

The limit is currently 50 characters.

**Comment by dmundra** [comment]
@mgifford can you review it again? Thank you for the continued feedback.

**Comment by mgifford** [comment]
Looks great now. Thanks @dmundra

**Review by mgifford — APPROVED** [review]
Nice ARIA addition

**Pull request merged**
