### PR TITLE
License field dropdown

### PR DESCRIPTION
**Pull request by dmundra**
Closes https://github.com/GSA/openacr/issues/224

**New report QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the About page.
4. Confirm you see the license field populated to CC-BY-4.0.
5. Click on the field and search for other licenses by typing or scrolling.
6. Confirm the search works and finds matching licenses.
7. Adjust the license and add some notes.
8. Click the 'View report' or 'Report' tab.
9. Confirm you see a 'Valid' message.
10. Confirm the HTML on the page displays the license selected (all the way to the bottom of the page).

**Existing report QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Click 'Open report'.
4. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' from https://github.com/GSA/openacr/tree/main/openacr.
5. Switch to the About page.
6. Confirm you see the license field populated to GPL-2.0-or-later.
7. Click on the field and search for other licenses by typing or scrolling.
8. Confirm the search works and finds matching licenses.
9. Adjust the license and add some notes.
10. Click the 'View report' or 'Report' tab.
11. Confirm you see a 'Valid' message.
12. Confirm the HTML on the page displays the license selected (all the way to the bottom of the page).

**Clear license QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the About page.
4. Confirm you see the license field populated to CC-BY-4.0.
5. Clear the license field.
6. Click the 'View report' or 'Report' tab.
7. Confirm you see a 'Valid' message.
8. Confirm the HTML on the page displays no license (all the way to the bottom of the page).

### CODE REVIEW

**Comment by mgifford** [comment]
This all works just fine, but what if you don't want an open license? The option to just fill in a Copyright isn't supported.  Lawyers might like Copyright @IBM 2022 

I wonder about how we might support other options better.

Also, the GPL is generally for code not content. CC-BY-4.0 is probably the one we want as a default.  Think we can cut down the number of options too.  Where is this list from?

**Comment by dmundra** [comment]
> This all works just fine, but what if you don't want an open license? The option to just fill in a Copyright isn't supported. Lawyers might like Copyright @IBM 2022
> 
> I wonder about how we might support other options better.
> 
> Also, the GPL is generally for code not content. CC-BY-4.0 is probably the one we want as a default. Think we can cut down the number of options too. Where is this list from?

The list comes from https://spdx.org/licenses/ and we did bake it into the validator to choose a license from that list so we could generate a URL. There is the legal disclaimer field as well.

I set 'CC-BY-4.0' as the default but I can remove the default and the section does not display. Thoughts?

**Comment by mgifford** [comment]
So if someone:
a) enters "Copyright @IBM 2022"; or 
b) deletes (or x) the placeholder

Can we (a) just display what they type (without text) display nothing, or (b) display nothing? 

I don't think that overwriting a) or b) with a CC-BY license is going to be well received. 

We can default to that if they do nothing (and might even put something in there about that being the preferred license for this document type) but there are going to be folks who are going to resist an open license.

**Comment by dmundra** [comment]
Since the validator will complain about custom entered text, I would say we go with option 'b' that they delete the license and it displays nothing. I will push up the change.

**Review by mgifford — APPROVED** [review]
Looks good. Thanks for making the adjustments.

**Pull request merged**
