### PR TITLE
Added component to create a header that can be focused on with an id …

### PR DESCRIPTION
**Pull request by dmundra**
…and anchor link. Added ids to other headers that didn't support a hidden anchor link. No table of contents right now, maybe later.

Closes https://github.com/GSA/openacr/issues/240

**Headers QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Visit the about, table/chapters, report, and acknowledgements pages.
3. Confirm for the different headers appear with an anchor link when you hover over it.
4. Click the anchor link and confirm it works.
5. Refresh the page and confirm you are still on the header.
6. Click the 'View report' or 'Report' tab.
7. Click the 'Download Report (HTML)' and confirm the HTML file headers have the same behavior

**Glossary QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Visit the glossary page.
3. Confirm for the different headers appear with an anchor link when you hover over it.
4. Click the anchor link and confirm it works.
5. Refresh the page and confirm you are still on the header.

### CODE REVIEW

**Comment by mgifford** [comment]
Ok, this looks great. Works well for mouse users, but not so well for keyboard users. with our implementation here https://accessibility.civicactions.com/calendar there is a link we can focus on for keyboard only users.

Couple minor things:
- shouldn't we add it to the Glossary too? https://gsa.github.io/openacr-editor/glossary
- I think it would be useful to link to the SC (i.e. 3.2.3 Consistent Navigation) in the report and not just the table https://gsa.github.io/openacr-editor/report#success_criteria_level_aa-editor

**Comment by dmundra** [comment]
> Ok, this looks great. Works well for mouse users, but not so well for keyboard users. with our implementation here https://accessibility.civicactions.com/calendar there is a link we can focus on for keyboard only users.

I can look into that.

> Couple minor things:
> 
> * shouldn't we add it to the Glossary too? https://gsa.github.io/openacr-editor/glossary

Glossary items are not headers so I didn't plan to add it there. Ids could be added to `dt` items. Do you also want the anchor links or should I change them to headers `<h2>`?

> * I think it would be useful to link to the SC (i.e. 3.2.3 Consistent Navigation) in the report and not just the table https://gsa.github.io/openacr-editor/report#success_criteria_level_aa-editor

There are IDs already. E.g. https://gsa.github.io/openacr-editor/report#consistent-behavior-consistent-locations-editor do you want the hidden anchor link available here as well?

**Comment by mgifford** [comment]
Adding it to the dt would be great. Thanks Dannie. And yes to making available the hidden anchor links.

**Comment by dmundra** [comment]
@mgifford I copied over the CA accessibility anchor link feature (credit: @jaube05). Give it a try now. I haven't finished adding all the headers to the glossary page but will try to finish that next.

Can you test the accessibility of the anchor links?

**Review by mgifford — APPROVED** [review]
Looks great!

**Pull request merged**
