### PR TITLE
Added download help text.

### PR DESCRIPTION
**Pull request by dmundra**
Closes https://github.com/GSA/openacr/issues/279

**QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Open report'.
3. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' or any of the yaml files from https://github.com/GSA/openacr/tree/main/openacr.
4. Click the 'View report' or 'Report' tab.
5. Review the download button and text below it.

### CODE REVIEW

**Comment by mgifford** [comment]
I don't think this is the right text here. Most of the time folks would just need to click the button.   The "follow these instructions" is only for people who have been limited to downloading the .zip file by the organization that employs the. 

Screen Shot of Report page

**Comment by danid123** [comment]
I don't see the changes when I load the editor @dmundra either with a blank report or with an existing one.
Screen Shot 2022-01-27 at 3 47 44 PM

Screen Shot 2022-01-27 at 3 52 53 PM

**Comment by dmundra** [comment]
@danid123 yup, the other PR #39 took the github pages for now. I will let that one merge, rebase this one and then we can review this again. I have a ticket in the backlog to allow us to handle multiple PRs in the future.

**Comment by dmundra** [comment]
@danid123 and @mgifford this is ready to be reviews when the checks complete.

**Review by mgifford — APPROVED** [review]
Looks great to me. Thanks @dmundra

**Pull request merged**
