### PR TITLE
About expanded by default, notes label change and fixed bug

### PR DESCRIPTION
**Pull request by dmundra**
Fixes https://github.com/GSA/openacr/issues/262 and fixes https://github.com/GSA/openacr/issues/263

**About page QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the about page.
4. Confirm all sections are expanded by default.

**Chapter pages QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the different table/chapter pages.
4. Confirm the text box label is set to 'Remarks and Explanations'
5. Add some markdown in the text box 
6. Click the 'View report' or 'Report' tab.
7. Confirm you see a 'Valid' message.
8. Confirm in the report you see in the 'Remarks and Explanations' column the markdown is correctly rendered.

### CODE REVIEW

**Comment by mgifford** [comment]
Yes. But what do we do with this **Note**:
Screen Shot of Note

My view is that we take this Chapter/Table Note section and just describe what to do with it in the description text we're going to write at the top of the page. This could be addressed here https://github.com/GSA/openacr/issues/261

**Review by mgifford — COMMENTED** [review]
Looks good. Nice catch with the reference to Markdown which is no longer supported.

**Comment by dmundra** [comment]
> Looks good. Nice catch with the reference to Markdown which is no longer supported.

Thanks @mgifford. Also agreed about handling the top notes in the other issue. Good to still approve this?

**Review by mgifford — APPROVED** [review]
All good

**Pull request merged**
