### PR TITLE
OpenACR chapter forms

### PR DESCRIPTION
**Pull request by dmundra**
Closes https://github.com/GSA/openacr/issues/207

QA steps:

**New report**
1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the different table/chapter pages.
4. Confirm you see form fields for chapter notes.
5. Confirm you see many criteria.
6. Confirm for A/AA/AAA you see multiple components with fields for level and notes.
7. Confirm for FPC, Hardware, Software, Docs you see only one field for level and notes.
8. Adjust the level and add some notes.
9. Click the 'View report' or 'Report' tab.
10. Confirm you see a 'Valid' message.
11. Click the 'Download Report (YAML)' and confirm the YAML file has the various chapters, criteria, and components filled out.

**Existing report**
1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Click 'Open report'.
4. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' or any of the yaml files from https://github.com/GSA/openacr/tree/main/openacr.
5. Switch to the different table/chapter pages.
6. Confirm you see the values in the fields from the yaml file for the criteria and components.
7. Adjust the level and add some notes.
8. Click the 'View report' or 'Report' tab.
9. Confirm you see a 'Valid' message.
10. Click the 'Download Report (YAML)' and confirm the YAML file has the various chapters, criteria, and components filled out.
11. Repeat the above steps with another yaml file.

### CODE REVIEW

**Comment by mgifford** [comment]
Why doesn't the HTML show? Values seem to appear in YAML & MD but not in the HTML pa
Screen Shot of multiple views of the same content
ge

**Comment by mgifford** [comment]
I think some other information should be in this html view too, right
Screen Shot of the final preview page for the report.
?

**Review by mgifford — COMMENTED** [review]
Looks good. Aside from the issues with missing HTML/Markdwon.  It works fine to export (and import) from YAML.  Just not seeing the content.

**Comment by dmundra** [comment]
> Looks good. Aside from the issues with missing HTML/Markdwon. It works fine to export (and import) from YAML. Just not seeing the content.

Thanks @mgifford for reviewing. I noted in the ticket https://github.com/GSA/openacr/issues/207#issuecomment-985688487 that I didn't work on HTML or Markdown yet as I wanted to get the forms for review first. In the next ticket and pull request I work on that.

**Review by mgifford — APPROVED** [review]
Looks good. @danid123 & I were looking at it earlier today.

**Pull request merged**
