### PR TITLE
Adjusted import new report to handle OpenACR yaml files

### PR DESCRIPTION
**Pull request by dmundra**
Closes https://github.com/GSA/openacr/issues/192

QA steps:

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Click 'Open report'.
4. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' or any of the yaml files from https://github.com/GSA/openacr/tree/main/openacr.
5. Switch to the 'About' page.
6. Confirm you see the values in the fields from the yaml file.
7. Click the 'View report' or 'Report' tab.
8. Confirm you see a 'Valid' message.
9. Confirm the HTML on the page displays the various sections except tables, chapters, related OpenACRs matching the YAML file.
10. Click the 'Download Report (HTML)' and confirm the HTML file downloaded matches the page.
11. Click the 'Download Report (Markdown)' and confirm the Markdown file downloaded matches the page.
12. Repeat the above steps with another yaml file.

### CODE REVIEW

**Comment by mgifford** [comment]
It doesn't seem to like any of the licenses I choose..
Screen Shot of report page with invalid message

**Comment by mgifford** [comment]
Related, the License is carried onto the HTMl templat
Screen Shot of license being added to HTML downoad

This seems to be part of the template.

**Review by mgifford — CHANGES_REQUESTED** [review]
@dmundra do you want to deal with these issues now or in the next PR? I think it would be fine to address them in the next round.

**Comment by dmundra** [comment]
> It doesn't seem to like any of the licenses I choose..

We use the 'Identifier' value in the field. Here is the issue https://github.com/GSA/openacr/issues/224 to convert it into a dropdown so you can pick from the website list.

> Related, the License is carried onto the HTMl templat ... This seems to be part of the template. Same with Markdown file.

Actually if the license field is empty then I default the footer to 'CC-BY-4.0' which is 'Creative Commons Attribution 4.0 International'

> @dmundra do you want to deal with these issues now or in the next PR? I think it would be fine to address them in the next round.

@mgifford, in the next PR related to the issue I created.

**Review by mgifford — APPROVED** [review]
Looks good,

**Pull request merged**
