### PR TITLE
Sanitizing markdown/html output on report

### PR DESCRIPTION
**Pull request by dmundra**
Fixes https://github.com/GSA/openacr/issues/306

Updated the markedjs package and installed a sanitize HTML package. Combined those in a function to sanitize any markdown and HTML added to textareas. Added few tests to check for that.

**QA**

1. After deployment ('Deploy' action) is successful, open site https://gsa.github.io/openacr-editor/.
2. Click 'Start new report' or 'New report'.
3. Switch to the different table/chapter pages.
4. Add some XSS HTML in the textareas. Use https://owasp.org/www-community/attacks/xss/ or other sources for examples.
5. Click the 'View report' or 'Report' tab.
6. Confirm you see a 'Valid' message.
7. Confirm in the report you see the content but don't get an alert popup or other XSS effect.

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford I am done with push changes. Let me know if you have any questions or need more XSS examples.

**Comment by mgifford** [comment]
So great to have tools like `sanitizeMarkdown()` to leverage. 

Works fine on the HTML report. It still exists in the YAML file though. I guess that is ok...

**Comment by dmundra** [comment]
> Works fine on the HTML report. It still exists in the YAML file though. I guess that is ok...

Good point. Should we sanitize their input to YAML as well? Probably yes.

**Review by mgifford — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
