### PR TITLE
261 add chapter help text

### PR DESCRIPTION
**Pull request by qjac**
Closes https://github.com/GSA/openacr/issues/261

Add yaml file with chapter introductory help text.
Create component to display help text and add that component to chapters and about page.
Add test to chapter suite to check that help text exists on those pages.

## QA
- Go to https://gsa.github.io/openacr-editor/
- Confirm that the correct chapter help text is displaying at the top of each page. [Mockup] (https://github.com/GSA/openacr/issues/261#issuecomment-1015720548) and [text](https://github.com/GSA/openacr/issues/261#issuecomment-1016449119) (note: minor text changes further in thread)
- Double check that text content is correct and is free of typos, including checking links in help text that includes links
- Confirm the new test in the chapter suite is 👍  and runs

### CODE REVIEW

**Comment by qjac** [comment]
I did not add specific instructions for running the code for QA. Is this a situation where one would pull it down locally to review? I'm not very clear on this process/flow.

**Comment by mgifford** [comment]
Just noticed the links only work if the first section is expanded https://gsa.github.io/openacr-editor/chapter/success_criteria_level_a#1.1.1-software-editor

Now we could just expand the first section by default, or expand when the item is clicked. But it doesn't work right now.

**Comment by mgifford** [comment]
Also the link from https://gsa.github.io/openacr-editor/chapter/software for "Tables 1, 2, and 3" goes to https://gsa.github.io/chapter/success_criteria_level_a and not https://gsa.github.io/openacr-editor/chapter/success_criteria_level_a

Think that is just a relative link error..

**Comment by danid123** [comment]
Ideal UX would be that the first section expands when you click the link but Mike's suggestion to just expand by default is fine too.

In the About section, there's a comma missing in the third sentence after the By phrase "By describing your product, the webform will update to show only the sections you need to fill out."

**Review by danid123 — CHANGES_REQUESTED** [review]
See previous comments

**Comment by dmundra** [comment]
> I did not add specific instructions for running the code for QA. Is this a situation where one would pull it down locally to review? I'm not very clear on this process/flow.

Nope, the changes will automatically get deployed (see the deploy GitHub action) to the GitHub pages site https://gsa.github.io/openacr-editor/ and it can be reviewed there.

For tests (I can see the number is now 44 🎉 ) they will get run in the GitHub action so doesn't need to be run locally either.

**Comment by dmundra** [comment]
> Ideal UX would be that the first section expands when you click the link but Mike's suggestion to just expand by default is fine too.

@qjac, @mgifford, @danid123 I think we should have [code already that opens the section](https://github.com/GSA/openacr-editor/blob/main/src/utils/honourFragmentIdLinks.js#L7-L10) when you click the anchor link but that might need to be tested. @mgifford can you make sure you clear your cache and try it again? Also let us know which browser you are using?

**Comment by mgifford** [comment]
Good reminders @dmundra I tested this the latest versions of Safari & Edge. I reloaded the page to verify.

**Comment by dmundra** [comment]
> Good reminders @dmundra I tested this the latest versions of Safari & Edge. I reloaded the page to verify.

Thanks for the browsers. It works on Chrome for me, @mgifford can you confirm that it works on Chrome for you.

@qjac I can co-work on this and test it out with you.

All, I think we might want to create a bug to tackle that issue and merge these changes once the text changes are confirmed so we don't hold these changes back. Thoughts? 

CC @mgifford and @danid123

**Comment by qjac** [comment]
That works for me @dmundra. I'm having a hard time wrapping my head around it, so a co-working session sounds useful!

I did make the requested text changes.

**Comment by qjac** [comment]
I also tested firefox and the drawers do not automatically open.

**Comment by dmundra** [comment]
Cool. @qjac can you make the bug in the backlog and assign you and me on it?

**Comment by qjac** [comment]
New issue/bug created. https://github.com/GSA/openacr/issues/288

**Review by dmundra — APPROVED** [review]
@qjac code looks great. Good use of a component for the help text. Also the test addition is great. Thank you for adding the bug.

@danid123 and @mgifford any text changes? I will defer to you both on that but those can be made later by modifying the `src/data/chapterHelpText.yaml` file after this is merged.

**Comment by danid123** [comment]
The text change looks good. Thank you!

When I tested it was on Chrome and it did not open.

**Review by danid123 — APPROVED** [review]

**Pull request merged**
